# -*- coding: utf-8 -*-
"""Climate Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11DuYpzhms2vC9MA0CUBEVUX0PW-oag7h
"""

# 1. Install and import the Kaggle tool
!pip install kagglehub pandas plotly
import kagglehub
import os
import pandas as pd
import plotly.express as px
from google.colab import files

print("Downloading dataset straight from Kaggle servers...")
# This pulls down the entire folder bundle instantly to Colab's cloud storage
folder_path = kagglehub.dataset_download("berkeleyearth/climate-change-earth-surface-temperature-data")

# Look inside the downloaded folder to locate the exact City CSV file
csv_file = os.path.join(folder_path, "GlobalLandTemperaturesByCity.csv")
print(f"Dataset successfully connected at path: {csv_file}")

print("\nParsing City dataset securely using safe-chunks...")
chunks = []
for chunk in pd.read_csv(csv_file, chunksize=100000, low_memory=False):
    # Filter for major cities inside Georgia, USA
    filtered_chunk = chunk[
        (chunk['Country'] == 'United States') &
        (chunk['City'].isin(['Atlanta', 'Savannah', 'Augusta', 'Columbus']))
    ].copy()
    chunks.append(filtered_chunk)

df = pd.concat(chunks, ignore_index=True)
print(f"🎉 Success! Found {len(df)} historical weather records for Georgia cities.")

# 2. Clean up dates and filter modern timeline (1900 - Present)
df['dt'] = pd.to_datetime(df['dt'], errors='coerce')
df = df.dropna(subset=['dt'])
df['Year'] = df['dt'].dt.year
df = df[df['Year'] >= 1900]

# 3. Convert text fields safely to numeric floats
df['AverageTemperature'] = pd.to_numeric(df['AverageTemperature'], errors='coerce')
df = df.dropna(subset=['AverageTemperature'])

# 4. Group by Year to get the unified regional temperature mean
annual_df = df.groupby('Year')['AverageTemperature'].mean().reset_index()

# 5. Convert Celsius to Fahrenheit
annual_df['Temp_Fahrenheit'] = (annual_df['AverageTemperature'] * 1.8) + 32

# 6. Calculate statistical 5-Year Moving Average
annual_df['5_Year_Moving_Avg'] = annual_df['Temp_Fahrenheit'].rolling(window=5).mean()

# 7. Render the dashboard UI layout
fig = px.line(
    annual_df,
    x='Year',
    y='Temp_Fahrenheit',
    title='Georgia Regional Climate Trend Dashboard (1900 - Present)',
    labels={'Temp_Fahrenheit': 'Mean Annual Temperature (°F)', 'Year': 'Timeline Year'},
    template='plotly_dark'
)

# Add our smoothed rolling line layer
fig.add_scatter(
    x=annual_df['Year'],
    y=annual_df['5_Year_Moving_Avg'],
    name='5-Year Trend Line',
    line=dict(color='orange', width=3)
)

fig.update_traces(mode='lines+markers', selector=dict(type='scatter', name='Temp_Fahrenheit'))
fig.update_layout(hovermode='x unified', title_x=0.5)

# 8. Display window & automatically push file download
fig.show()
fig.write_html('climate_dashboard.html')
files.download('climate_dashboard.html')